# Scientific Computations and Data Transformations with Python

### Math

In [10]:
import math

In [11]:
print(math.pow(7, 2))
print(7 ** 2)

print(math.sqrt(64))

49.0
49
8.0


In [12]:
print(round(24.63))
print(round(24.47))

print(math.floor(28.73))
print(math.ceil(28.36))

25
24
28
29


In [13]:
print(math.exp(2))
print(math.pi)

7.38905609893065
3.141592653589793


In [15]:
print(math.factorial(5))

120


### Time

In [19]:
import time

In [23]:
curr_date_time = time.ctime()
print(curr_date_time)

Mon Mar 11 09:49:05 2024


In [36]:
print(time.gmtime()) #GMT Time

print(time.gmtime().tm_year)
print(time.gmtime().tm_zone)

time.struct_time(tm_year=2024, tm_mon=3, tm_mday=11, tm_hour=4, tm_min=25, tm_sec=24, tm_wday=0, tm_yday=71, tm_isdst=0)
2024
UTC


In [32]:
for count in range(3):
    print(f"Count: {count + 1}")
    time.sleep(2)

Count: 1
Count: 2
Count: 3


In [38]:
curr_local_time = time.localtime()

print(curr_local_time.tm_mon)
print(curr_local_time.tm_mday)

print(curr_local_time.tm_hour)
print(curr_local_time.tm_min)


3
11
9
57


In [42]:
print(type(curr_date_time))

<class 'str'>


#### strftime -> Converts Time Struct to String

In [54]:
date_time = time.localtime()
date_time_str = time.strftime("%Y-%m-%d %H:%M:%S", date_time)

print(date_time_str)

2024-03-11 10:19:49


#### strptime -> Converts String to Time Struct

In [57]:
date_time_str = "2024-03-11 11:30:00"
date_time = time.strptime(date_time_str, "%Y-%m-%d %H:%M:%S")
print(date_time)

time.struct_time(tm_year=2024, tm_mon=3, tm_mday=11, tm_hour=11, tm_min=30, tm_sec=0, tm_wday=0, tm_yday=71, tm_isdst=-1)


### Regular Expression Matching (Regex)

In [1]:
import re

In [2]:
pattern = re.compile("Warm")
pattern.search("Global Warming")

<re.Match object; span=(7, 11), match='Warm'>

In [77]:
ob = re.search("al", "Global Warming")
print(ob)
print(ob.group())

<re.Match object; span=(4, 6), match='al'>
al


In [6]:
re.findall("ing", "Global Warming is a concerning issue")

['ing', 'ing']

In [87]:
print(re.search(".*", "Digital @ 79 Era") is not None)
print(re.search(".+", "Digital @ 79 Era") is not None)

print(re.search("Z*", "Digital @ 79 Era") is not None)
print(re.search("Z+", "Digital @ 79 Era") is not None)

True
True
True
False


In [82]:
print(re.search("^D", "Digital @ 79 Era") is not None)
print(re.search("^[A-Za-z]", "Digital @ 79 Era") is not None)
print(re.search("^[A-C]", "Digital @ 79 Era") is not None)

print(re.search("a$", "Digital @ 79 Era") is not None)
print(re.search("[b-e]$", "Digital @ 79 Era") is not None)

True
True
False
True
False


In [213]:
print(re.search("[0-9]", "Digital @ 79 Era") is not None)
print(re.search("[0-5]", "Digital @ 79 Era") is not None)

True
False


In [214]:
print(re.search("@+", "Digital @ 79 Era") is not None)

print(re.search("\$+", "Digital $ 79 Era") is not None)
print(re.search("\^+", "Digital ^ 79 Era") is not None)
print(re.search(rf"\\+", "Digital \ 79 Era") is not None)

print(re.search("\ +", "Digital79Era") is not None)


True
True
True
True
False


In [146]:
print(re.findall("[ABC]", "INDIA"))
print(re.findall("[^ABC]", "INDIA"))
print(re.findall("[XYZ]", "INDIA"))

['A']
['I', 'N', 'D', 'I']
[]


In [219]:
print(re.search("\d", "ABCDE") is not None)
print(re.search("\d", "ABCDE457") is not None)

print(re.search("\D", "ABCDE") is not None)
print(re.search("\D", "457") is not None)

print(re.search("\w", "ABCDE457") is not None)
print(re.search("\w", "#@ *^$") is not None)

print(re.search("\W", "#@ *^$") is not None)

False
True
True
False
True
False
True


In [179]:
print(re.search("A{1}", "AAABCD") is not None)
print(re.search("A{4}", "AAABCD") is not None)
print(re.search("A{1,3}", "AAABCD") is not None)
print(re.search("A{4,10}", "AAABCD") is not None)
print(re.search("A{3,}", "AAABCD") is not None)

print(re.search("[ABC]{1}", "INDIA") is not None)
print(re.search("[ABC]{1}", "EGYPT") is not None)

True
False
True
False
True
True
False


### JSON Data Manipulation

In [224]:
import json

In [238]:
customers_str = '{"id": "101","name": "Paul Brandon","age": "35","active": "Yes"}'

In [242]:
customers_json_ob = json.loads(customers_str)
print(customers_json_ob)
print(type(customers_json_ob))

{'id': '101', 'name': 'Paul Brandon', 'age': '35', 'active': 'Yes'}
<class 'dict'>


In [243]:
customers_json_ob["name"]

'Paul Brandon'

In [244]:
customer_res_str = json.dumps(customers_json_ob)
customer_res_str

'{"id": "101", "name": "Paul Brandon", "age": "35", "active": "Yes"}'

In [245]:
cust_dict = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}

cust_str = json.dumps(cust_dict)

In [246]:
cust_str

'{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cars": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.1}]}'

### Numpy

1. Numpy is core library used for scientific and numerical computing.
2. It provided high performance multi-dimensional arrays.
3. It is fast, conventional(lot of functions) and consumes less memory.


In [109]:
import numpy as np

In [110]:
items = np.array([(1,2,3),(4,5,6),(1,4,6),(7,3,6)], dtype=int)
print(items)

[[1 2 3]
 [4 5 6]
 [1 4 6]
 [7 3 6]]


In [111]:
zeros = np.zeros((3,4), dtype=int)
print(zeros)

ones = np.ones((3,4), dtype=float)
print(ones)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [112]:
ar_range = np.arange(5,12,2)
print(ar_range)

ar_lin = np.linspace(0,2,9)
print(ar_lin)

[ 5  7  9 11]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [113]:
ar_full = np.full((2,3), 7)
print(ar_full)

idMat = np.eye(3)
print(idMat)

[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [114]:
ar_rand = np.random.rand(3,4)
print(ar_rand)

ar_randint = np.random.randint(4, size=(5,3))
print(ar_randint)

[[0.55391756 0.76598401 0.82256334 0.56374045]
 [0.64061322 0.60980195 0.42191012 0.80122747]
 [0.25741793 0.4955135  0.90357482 0.94895124]]
[[2 1 0]
 [1 3 0]
 [0 2 1]
 [1 0 0]
 [1 3 1]]


In [118]:
items = np.array([(1,2,3),(4,5,6),(1,4,6),(7,3,6)], dtype=int)
items

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 6],
       [7, 3, 6]])

In [119]:
#Across Row
for itr in np.nditer(items, order='C'):
    print(itr, end=' ')
print()

#Across Col
for itr in np.nditer(items, order='F'):
    print(itr, end=' ')
print()

1 2 3 4 5 6 1 4 6 7 3 6 
1 4 1 7 2 5 4 3 3 6 6 6 


In [120]:
print(items.shape) #dimensions (rows,columns)
print(len(items)) #No.of.rows
print(items.ndim) #dimensions (1D or 2D or any)
print(items.size) #tot elements
print(items.dtype) #datatype of elements
print(items.astype(float))

(4, 3)
4
2
12
int32
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 4. 6.]
 [7. 3. 6.]]


#### Custom Data Types

In [121]:
customer_dtype = [("Name", "S10"), ("Age", int), ("isActive", bool)]
customer_values = [("Paul", 36, True), ("Tina", 32, True), ("John", 45, False), ("Ken", 23, True)]

customers_array = np.array(customer_values, dtype=customer_dtype)
customers_array

array([(b'Paul', 36,  True), (b'Tina', 32,  True), (b'John', 45, False),
       (b'Ken', 23,  True)],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('isActive', '?')])

In [122]:
customers_array["Name"]

array([b'Paul', b'Tina', b'John', b'Ken'], dtype='|S10')

#### Arthithmetic Operations

In [123]:
ar = np.array([(2, 3, 4), (1, 2, 6), (5, 1, 3)], dtype = int)

In [124]:
print(np.add(ar, [10, 20, 30]))
print(np.subtract(ar, [1, 2, 3]))
print(np.multiply(ar, [1, 2, 3]))
print(np.divide(ar, [2, 3, 4]))

[[12 23 34]
 [11 22 36]
 [15 21 33]]
[[ 1  1  1]
 [ 0  0  3]
 [ 4 -1  0]]
[[ 2  6 12]
 [ 1  4 18]
 [ 5  2  9]]
[[1.         1.         1.        ]
 [0.5        0.66666667 1.5       ]
 [2.5        0.33333333 0.75      ]]


In [125]:
ar1 = np.array([(3, 4, 5), (2, 1, 3)])
ar2 = np.array([(2, 2, 6), (7, 2, 1)])

print(ar1 + ar2)
print(ar1 - ar2)
print(ar1 * ar2)
print(ar1 / ar2)


[[ 5  6 11]
 [ 9  3  4]]
[[ 1  2 -1]
 [-5 -1  2]]
[[ 6  8 30]
 [14  2  3]]
[[1.5        2.         0.83333333]
 [0.28571429 0.5        3.        ]]


#### Comparision

In [126]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[1,2],[3,4]])

print(ar1 > 1)
print(ar1 == ar2)
print(np.array_equal(ar1, ar2))

[[False  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
True


#### Aggregate Functions

In [127]:
ar = np.array([(1,2,3),(3,4,5)])

In [128]:
print(ar.sum()) #sum(all elements)
print(ar.sum(axis=1)) #sum(each row)
print(ar.sum(axis=0)) #sum(each column)
print(ar.min(), ar.max())
print(ar.mean())

18
[ 6 12]
[4 6 8]
1 5
3.0


#### Array Copying/Cloning

In [129]:
ar_view = ar.view()
ar_view

array([[1, 2, 3],
       [3, 4, 5]])

In [130]:
ar_clone = ar.copy()
ar_clone

array([[1, 2, 3],
       [3, 4, 5]])

#### Sorting

In [131]:
ar = np.array([3,6,2,5,1])

print(np.sort(ar))

[1 2 3 5 6]


In [132]:
unordered = np.array([[7,6,5],[4,9,8]])
print("Original Array:")
print(unordered)

print("Row wise Sorted Array:")
print(np.sort(unordered, axis=1)) #Across the row

print("Column wise Sorted Array:")
print(np.sort(unordered, axis=0)) #Across the col

print("Flatened Sorted Array:")
print(np.sort(unordered, axis=None))

Original Array:
[[7 6 5]
 [4 9 8]]
Row wise Sorted Array:
[[5 6 7]
 [4 8 9]]
Column wise Sorted Array:
[[4 6 5]
 [7 9 8]]
Flatened Sorted Array:
[4 5 6 7 8 9]


In [133]:
customers_array

array([(b'Paul', 36,  True), (b'Tina', 32,  True), (b'John', 45, False),
       (b'Ken', 23,  True)],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('isActive', '?')])

In [134]:
print(np.sort(customers_array, order="Age"))

[(b'Ken', 23,  True) (b'Tina', 32,  True) (b'Paul', 36,  True)
 (b'John', 45, False)]


#### Subsetting and Slicing

In [135]:
items = np.array([[3,4,2],[8,7,9],[4,3,5]])
print(items[2][0])

4


In [136]:
items = np.arange(4,25,2)
items

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [137]:
print(items[::3])
print(items[2:7])
print(items[3:8:2]) #start, end, steps
print(items[::-1])
print(items[items>10])

[ 4 10 16 22]
[ 8 10 12 14 16]
[10 14 18]
[24 22 20 18 16 14 12 10  8  6  4]
[12 14 16 18 20 22 24]


In [138]:
ar_ones = np.ones((4,4), dtype=int)
print(ar_ones)

ar_ones[0::2, 1::2] = 0
print(ar_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 0 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 1 1 1]]


### Array Manipulation

#### Append, Insert and Delete

In [152]:
ar = np.array(['a','b','c','d','e','f'])
ar

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [153]:
print(np.append(ar, values = ['m', 'n']))

print(np.insert(ar, obj = 2, values = ['k', 'j']))

print(np.delete(ar, obj = [1, 4]))

['a' 'b' 'c' 'd' 'e' 'f' 'm' 'n']
['a' 'b' 'k' 'j' 'c' 'd' 'e' 'f']
['a' 'c' 'd' 'f']


#### Reshaping, Resizing and Transposing

In [154]:
ar_1X12 = np.arange(1,13)

ar_3X4 = ar_1X12.reshape(3,4)
print(ar_3X4)

ar_4X3 = ar_3X4.reshape(4,3)
print(ar_4X3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [161]:
ar = np.array([['a','b'],['c','d'],['e','f']])
ar

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [162]:
print(ar.reshape(2,3))
print(ar.reshape(2,4)) #Throws Error

[['a' 'b' 'c']
 ['d' 'e' 'f']]


ValueError: cannot reshape array of size 6 into shape (2,4)

In [163]:
print(np.resize(ar, (2,4))) #Doesn't throw error, the sequence of elements will be repeated

[['a' 'b' 'c' 'd']
 ['e' 'f' 'a' 'b']]


In [164]:
print(np.transpose(ar)) #Converts Rows to Cols and Vice-Versa

[['a' 'c' 'e']
 ['b' 'd' 'f']]


#### Flattening

In [167]:
ar

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [168]:
print(ar.flatten()) #default order='C' i.e across row
print(ar.flatten(order='F')) #across col

['a' 'b' 'c' 'd' 'e' 'f']
['a' 'c' 'e' 'b' 'd' 'f']


#### Concatenating

In [169]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])

print(np.concatenate((ar1, ar2), axis=0)) #col-wise
print(np.concatenate((ar1, ar2), axis=1)) #row-wise

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Splitting

In [170]:
ar = np.arange(9)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
print(np.split(ar, 3))
print(np.split(ar, [4,5]))
print(np.split(ar, [2,4,6]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7, 8])]


### Others

In [178]:
ar = np.array([[1, 2, np.nan], [np.nan, 2, np.nan], [np.inf, 2, np.nan]])
ar

array([[ 1.,  2., nan],
       [nan,  2., nan],
       [inf,  2., nan]])

In [179]:
print(np.isnan(ar))
print(np.isnan(ar).sum())

[[False False  True]
 [ True False  True]
 [False False  True]]
4


In [183]:
print(np.isfinite(ar).sum())
print(np.isinf(ar))

4
[[False False False]
 [False False False]
 [ True False False]]


In [184]:
print(np.char.add(['a','b'],['c','d']))
print(np.char.lower("AXION"))
print(np.char.capitalize("numpy"))
print(np.char.center("Data", 20, '*'))

['ac' 'bd']
axion
Numpy
********Data********
