## Numpy

1. Numpy is core library used for scientific and numerical computing.
2. It provided high performance multi-dimensional arrays.
3. It is fast, conventional(lot of functions) and consumes less memory.


In [3]:
import numpy as np

In [4]:
items = np.array([(1,2,3),(4,5,6),(1,4,6),(7,3,6)], dtype=int)
print(items)

[[1 2 3]
 [4 5 6]
 [1 4 6]
 [7 3 6]]


In [5]:
zeros = np.zeros((3,4), dtype=int)
print(zeros)

ones = np.ones((3,4), dtype=float)
print(ones)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
ar_range = np.arange(5,12,2)
print(ar_range)

ar_lin = np.linspace(0,2,9)
print(ar_lin)

[ 5  7  9 11]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [8]:
ar_lin = np.linspace(1,100,10)
print(ar_lin)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [9]:
ar_full = np.full((2,3), 7)
print(ar_full)

idMat = np.eye(3)
print(idMat)

[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
ar_rand = np.random.rand(3,4)
print(ar_rand)

ar_randint = np.random.randint(4, size=(5,3))
print(ar_randint)

[[0.20282229 0.65209769 0.63980614 0.78289796]
 [0.96711095 0.1063168  0.31963462 0.58521446]
 [0.62928236 0.95023291 0.27574749 0.57225315]]
[[2 3 0]
 [3 3 2]
 [0 0 3]
 [2 3 0]
 [2 2 2]]


In [11]:
items = np.array([(1,2,3),(4,5,6),(1,4,6),(7,3,6)], dtype=int)
items

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 6],
       [7, 3, 6]])

In [12]:
#Across Row
for itr in np.nditer(items, order='C'):
    print(itr, end=' ')
print()

#Across Col
for itr in np.nditer(items, order='F'):
    print(itr, end=' ')
print()

1 2 3 4 5 6 1 4 6 7 3 6 
1 4 1 7 2 5 4 3 3 6 6 6 


In [13]:
print(items.shape) #dimensions (rows,columns)
print(len(items)) #No.of.rows
print(items.ndim) #dimensions (1D or 2D or any)
print(items.size) #tot elements
print(items.dtype) #datatype of elements

(4, 3)
4
2
12
int64


In [14]:
print(items.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 4. 6.]
 [7. 3. 6.]]


#### Custom Data Types

In [15]:
customer_dtype = [("Name", "S10"), ("Age", int), ("isActive", bool)]
customer_values = [("Paul", 36, True), ("Tina", 32, True), ("John", 45, False), ("Ken", 23, True)]

customers_array = np.array(customer_values, dtype=customer_dtype)
customers_array

array([(b'Paul', 36,  True), (b'Tina', 32,  True), (b'John', 45, False),
       (b'Ken', 23,  True)],
      dtype=[('Name', 'S10'), ('Age', '<i8'), ('isActive', '?')])

In [16]:
customers_array["Name"]

array([b'Paul', b'Tina', b'John', b'Ken'], dtype='|S10')

#### Arthithmetic Operations

In [17]:
ar = np.array([(2, 3, 4), (1, 2, 6), (5, 1, 3)], dtype = int)

In [18]:
print(np.add(ar, [10, 20, 30]))
print(np.subtract(ar, [1, 2, 3]))
print(np.multiply(ar, [1, 2, 3]))
print(np.divide(ar, [2, 3, 4]))

[[12 23 34]
 [11 22 36]
 [15 21 33]]
[[ 1  1  1]
 [ 0  0  3]
 [ 4 -1  0]]
[[ 2  6 12]
 [ 1  4 18]
 [ 5  2  9]]
[[1.         1.         1.        ]
 [0.5        0.66666667 1.5       ]
 [2.5        0.33333333 0.75      ]]


In [19]:
ar1 = np.array([(3, 4, 5), (2, 1, 3)])
ar2 = np.array([(2, 2, 6), (7, 2, 1)])

print(ar1 + ar2)
print(ar1 - ar2)
print(ar1 * ar2)
print(ar1 / ar2)


[[ 5  6 11]
 [ 9  3  4]]
[[ 1  2 -1]
 [-5 -1  2]]
[[ 6  8 30]
 [14  2  3]]
[[1.5        2.         0.83333333]
 [0.28571429 0.5        3.        ]]


#### Comparision

In [20]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[1,2],[3,4]])

print(ar1 > 1)
print(ar1 == ar2)
print(np.array_equal(ar1, ar2))

[[False  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
True


#### Aggregate Functions

In [21]:
ar = np.array([(1,2,3),(3,4,5)])

In [22]:
print(ar.sum()) #sum(all elements)
print(ar.sum(axis=1)) #sum(each row)
print(ar.sum(axis=0)) #sum(each column)
print(ar.min(), ar.max())
print(ar.mean())

18
[ 6 12]
[4 6 8]
1 5
3.0


#### Array Copying/Cloning

In [23]:
ar_view = ar.view()
ar_view

array([[1, 2, 3],
       [3, 4, 5]])

In [24]:
ar_clone = ar.copy()
ar_clone

array([[1, 2, 3],
       [3, 4, 5]])

#### Sorting

In [25]:
ar = np.array([3,6,2,5,1])

print(np.sort(ar))

[1 2 3 5 6]


In [26]:
unordered = np.array([[7,6,5],[4,9,8]])
print("Original Array:")
print(unordered)

print("Row wise Sorted Array:")
print(np.sort(unordered, axis=1)) #Across the row

print("Column wise Sorted Array:")
print(np.sort(unordered, axis=0)) #Across the col

print("Flatened Sorted Array:")
print(np.sort(unordered, axis=None))

Original Array:
[[7 6 5]
 [4 9 8]]
Row wise Sorted Array:
[[5 6 7]
 [4 8 9]]
Column wise Sorted Array:
[[4 6 5]
 [7 9 8]]
Flatened Sorted Array:
[4 5 6 7 8 9]


In [27]:
customers_array

array([(b'Paul', 36,  True), (b'Tina', 32,  True), (b'John', 45, False),
       (b'Ken', 23,  True)],
      dtype=[('Name', 'S10'), ('Age', '<i8'), ('isActive', '?')])

In [28]:
print(np.sort(customers_array, order="Age"))

[(b'Ken', 23,  True) (b'Tina', 32,  True) (b'Paul', 36,  True)
 (b'John', 45, False)]


#### Subsetting and Slicing

In [29]:
items = np.array([[3,4,2],[8,7,9],[4,3,5]])
print(items[2][0])

4


In [30]:
items = np.arange(4,25,2)
items

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
print(items[::3])
print(items[2:7])
print(items[3:8:2]) #start, end, steps
print(items[::-1])

[ 4 10 16 22]
[ 8 10 12 14 16]
[10 14 18]
[24 22 20 18 16 14 12 10  8  6  4]


In [33]:
print(items[items>10])

[12 14 16 18 20 22 24]


In [34]:
ar_ones = np.ones((4,4), dtype=int)
print(ar_ones)

ar_ones[0::2, 1::2] = 0
print(ar_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 0 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 1 1 1]]


### Array Manipulation

#### Append, Insert and Delete

In [35]:
ar = np.array(['a','b','c','d','e','f'])
ar

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [36]:
print(np.append(ar, values = ['m', 'n']))

print(np.insert(ar, obj = 2, values = ['k', 'j']))

print(np.delete(ar, obj = [1, 4]))

['a' 'b' 'c' 'd' 'e' 'f' 'm' 'n']
['a' 'b' 'k' 'j' 'c' 'd' 'e' 'f']
['a' 'c' 'd' 'f']


#### Reshaping, Resizing and Transposing

In [37]:
ar_1X12 = np.arange(1,13)
print(ar_1X12)

ar_3X4 = ar_1X12.reshape(3,4)
print(ar_3X4)

ar_4X3 = ar_3X4.reshape(4,3)
print(ar_4X3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
ar = np.array([['a','b'],['c','d'],['e','f']])
ar

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [39]:
print(ar.reshape(2,3))

[['a' 'b' 'c']
 ['d' 'e' 'f']]


In [40]:
print(ar.reshape(2,4)) #Throws Error

ValueError: cannot reshape array of size 6 into shape (2,4)

In [41]:
print(np.resize(ar, (2,4))) #Doesn't throw error, the sequence of elements will be repeated

[['a' 'b' 'c' 'd']
 ['e' 'f' 'a' 'b']]


In [42]:
print(np.transpose(ar)) #Converts Rows to Cols and Vice-Versa

[['a' 'c' 'e']
 ['b' 'd' 'f']]


#### Flattening

In [43]:
ar

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [44]:
print(ar.flatten()) #default order='C' i.e across row
print(ar.flatten(order='F')) #across col

['a' 'b' 'c' 'd' 'e' 'f']
['a' 'c' 'e' 'b' 'd' 'f']


#### Concatenating

In [46]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])

print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [47]:
print(np.concatenate((ar1, ar2), axis=0)) #col-wise
print(np.concatenate((ar1, ar2), axis=1)) #row-wise

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Splitting

In [48]:
ar = np.arange(9)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
print(np.split(ar, 3))
print(np.split(ar, [4,5]))
print(np.split(ar, [2,4,6]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7, 8])]


### Others

In [56]:
ar = np.array([[1, 2, np.nan], [np.nan, 2, 6], [np.inf, 2, np.nan]])
ar

array([[ 1.,  2., nan],
       [nan,  2.,  6.],
       [inf,  2., nan]])

In [57]:
print(np.isnan(ar))
print(np.isnan(ar).sum())

[[False False  True]
 [ True False False]
 [False False  True]]
3


In [58]:
print(np.isinf(ar))
print(np.isinf(ar).sum())

[[False False False]
 [False False False]
 [ True False False]]
1


In [59]:
print(np.isfinite(ar).sum())

5


In [60]:
print(np.char.add(['a','b'],['c','d']))
print(np.char.lower("AXION"))
print(np.char.capitalize("numpy"))
print(np.char.center("Data", 20, '*'))

['ac' 'bd']
axion
Numpy
********Data********
